### ISSUE TITLE
Archives missing

### ISSUE THREAD

**Issue by stevens-Ai** [SelennLamson/AITextGenerator#15]
None of the archive links work.

**Comment by SelennLamson** [comment]
Hi, the project was a school project made a while ago, and we didn't plan to maintain it further. It gained some visibility in the recent years with the GPT success, but I don't plan to fix the issues on it, I'm afraid - I understand this might not be satisfactory to you, I'm sorry for this.
Also, I must say that the models used in this project are now quite old, and I would strongly recommend starting over with the new available techologies!
